export type Restaurant = {
  id: string;
  score?: number;
  disliked?: boolean;
  userScore: number;
  hidden?: boolean;
  vetoed?: boolean;
  unseen?: boolean;
  approvedByUser?: 0 | 1 | -1;
  name?: string;
  address?: string;
  location?: { latitude: string; longitude: string };
  open?: boolean;
  inBudget?: boolean;
  rating?: number | null;
  priceLevel?: string;
  rating_count?: number;
  hours?: Array<string>;
  photos?: Array<string>;
  types?: Array<string>;
  accessibilityOptions?: any;
  website?: string;
};
